#pragma once

#include "includes.h"

#define VERSION          "v0.01 (05/29/2024)"

#define TITLE_BAR_X             0
#define TITLE_BAR_Y             0

#define TITLE_TEXT_X            3    
#define TITLE_TEXT_Y            0

#define VERSION_TEXT_X         61
#define VERSION_TEXT_Y          0

#define STATUS_X1              52
#define STATUS_Y1               2
#define STATUS_X2              74
#define STATUS_Y2               1


#define STATUS_LEVEL_TEXT_X
#define STATUS_LEVEL_TEXT_Y
#define STATUS_CATEGORY_TEXT_X
#define STATUS_CATEGORY_TEXT_Y
#define STATUS_TIME_TEXT_X
#define STATUS_TIME_TEXT_Y
#define STATUS_LEVEL_X
#define STATUS_LEVEL_Y
#define STATUS_CATEGORY_X
#define STATUS_CATEGORY_Y
#define STATUS_TIME_X
#define STATUS_TIME_Y

#define BUTTONS_AREA_X1
#define BUTTONS_AREA_Y1
#define BUTTONS_AREA_X2
#define BUTTONS_AREA_Y2
#define BUTTON_V_DIVIDER_X
#define BUTTON_V_DIVIDER_Y
#define BUTTON_V_DIVIDER_LEN
#define BUTTON_H1_DIVIDER_X
#define BUTTON_H1_DIVIDER_Y
#define BUTTON_H2_DIVIDER_X
#define BUTTON_H2_DIVIDER_Y
#define BUTTON_H_DIVIDER_W
#define BUTTON_HELP_X
#define BUTTON_HELP_Y
#define BUTTON_OPTS_X
#define BUTTON_OPTS_Y
#define BUTTON_SAVE_X
#define BUTTON_SAVE_Y
#define BUTTON_LOAD_X
#define BUTTON_LOAD_Y
#define BUTTON_MARK_X
#define BUTTON_MARK_Y
#define BUTTON_EXIT_X
#define BUTTON_EXIT_Y

// The position of the largest puzzle area. This will move depending on the puzzle size
// We'll try to calculate the positions based on the puzzle size and these constants.
#define PUZZLE_AREA_MIN_X   20
#define PUZZLE_AREA_MIN_Y   10

#define PUZZLE_TOP_AREA_MIN_X1       19
#define PUZZLE_TOP_AREA_MIN_Y1        2
#define PUZZLE_TOP_AREA_MIN_X2       44
#define PUZZLE_TOP_AREA_MIN_Y2        9